runtime: php
env: flex

runtime_config:
  document_root: public
  enable_stackdriver_integration: true

# Ensure we skip ".env", which is only for local development

env_variables:
  # Put production environment variables here.
  APP_KEY: base64:B25yE1A7qIXy7WGKAG+NfMsULWoTjolnL21SSLfNeuE=
  VIEW_COMPILED_PATH: /tmp
  STORAGE_PATH: /tmp
  DB_CONNECTION: mysql
  DB_SOCKET: '/cloudsql/bodywizard:us-central1:ehr-data'
  DB_PORT: 3306
  DB_DATABASE: 'bodywizard_ehr'
  DB_USERNAME: 'david'
  DB_PASSWORD: 'b0nerzFTW'
  LOG_CHANNEL: 'stackdriver'
  SESSION_DRIVER: database
  SESSION_LIFETIME: 30
  APP_BOOTSTRAP_CACHE: /tmp
  PUSHER_APP_ID: 975191
  PUSHER_APP_KEY: 5ffc0c92650faf3d8afd
  PUSHER_APP_SECRET: 76a3a8932dd475ae7dae
  BROADCAST_DRIVER: pusher
  STRIPE_KEY: pk_test_kmcewhdhAU5eVmRdauVQm76y00eDfxXBUG
  STRIPE_SECRET: sk_test_VO8cEI3MbKfcxeHOLlpjBOfa009mq5Zrze
  TWILIO_SID: ACa92309230eb92edec1b86837aca5cd4b
  TWILIO_TOKEN: d52deab2c8e7b9683c52cd67a0a45b54
  TWILIO_FROM: 15125808399

beta_settings:
  cloud_sql_instances: 'bodywizard:us-central1:ehr-data'

resources: 
  cpu: 2
  memory_gb: 1.4

automatic_scaling:
  min_num_instances: 1
  cpu_utilization:
    target_utilization: 0.7