runtime: php
env: flex

runtime_config:
  document_root: public
  enable_stackdriver_integration: true

# Ensure we skip ".env", which is only for local development

env_variables:
  # Put production environment variables here.
  APP_KEY: base64:B25yE1A7qIXy7WGKAG+NfMsULWoTjolnL21SSLfNeuE=
  VIEW_COMPILED_PATH: /tmp
  DB_CONNECTION: mysql
  DB_SOCKET: '/cloudsql/bodywizard:us-central1:ehr-data'
  DB_PORT: 3306
  DB_DATABASE: 'bodywizard_ehr'
  DB_USERNAME: 'david'
  DB_PASSWORD: 'b0nerzFTW'
  LOG_CHANNEL: 'stackdriver'
  SESSION_DRIVER: database
  SESSION_LIFETIME: 30
  APP_BOOTSTRAP_CACHE: /tmp

beta_settings:
  cloud_sql_instances: 'bodywizard:us-central1:ehr-data'

automatic_scaling:
  min_num_instances: 1
  cpu_utilization:
    target_utilization: 0.7